"""End-to-end driver (spec §5 outputs, §8 acceptance, §12 staged publish).

Usage:
  python run.py data/fredmd_2026-07.csv
  python run.py --vintage 2026-08            # downloads data/fredmd_2026-08.csv first
Options: --trend-window 240 --theta 0.5 --no-walkforward --wf-step 1 --wf-min-obs 240
         --skip-robustness --skip-expanding --out-dir output --figs-dir figs --data-sheet data/README.md
Exit code 1 and no publish if any §8 threshold fails; staged results stay in <out-dir>.staging/.
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
import urllib.request
from pathlib import Path

import numpy as np
import pandas as pd

from regime_v2 import acceptance, assets, figures, portfolio, regimes as R
from regime_v2.data import GROWTH_BLOCK, INFLATION_BLOCK
from regime_v2.factors import pca_factor_expanding
from regime_v2.pipeline import DEFAULTS, labels_frame, run_pipeline
from regime_v2.trend import centred_trend_expost, revision_stats
from regime_v2.walkforward import fit_hmm4_walkforward

HERE = Path(__file__).resolve().parent
# Spec §6 Stage 1: verified 2026-09-04 against the St. Louis Fed FRED-MD page —
# monthly vintages are named YYYY-MM-md.csv under /-/media/...; the older
# files.stlouisfed.org pattern is kept as a fallback.
FREDMD_URLS = [
    "https://www.stlouisfed.org/-/media/project/frbstl/stlouisfed/research/fred-md/monthly/{vintage}-md.csv",
    "https://files.stlouisfed.org/files/htdocs/fred-md/monthly/{vintage}.csv",
]
FREDMD_URL = FREDMD_URLS[0]   # kept for callers/tests that format a single pattern
FIG_NAMES = ["fig1_factors_gaps", "fig2_regime_timeline", "fig3_state_space", "fig4_hmm_probabilities",
             "fig5_revisions", "fig6_classifier_comparison", "fig7_walkforward"]
# Everything the asset stage publishes, so a run can clear the previous run's asset
# artefacts before it starts and only put its own in place once the stage succeeded.
ASSET_CSVS = ["regime_returns.csv", "backtest_returns.csv", "portfolio_weights.csv"]
ASSET_CSV_GLOBS = ["regime_corr_*.csv"]
ASSET_FIGS = ["fig8_regime_returns", "fig9_mixture_6040", "fig10_backtest_wealth", "fig11_pit_weights"]
ASSETS_STAGING = ".assets_staging"


def download_vintage(vintage: str, dest_dir: Path, fetch=urllib.request.urlopen) -> Path:
    """Download one FRED-MD vintage, trying each known URL pattern in turn."""
    dest_dir = Path(dest_dir); dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / f"fredmd_{vintage}.csv"
    errors = []
    for template in FREDMD_URLS:
        url = template.format(vintage=vintage)
        try:
            with fetch(url, timeout=60) as r:
                dest.write_bytes(r.read())
            return dest
        except Exception as e:  # urllib.error.HTTPError / URLError / OSError
            errors.append(f"{url}: {e}")
    raise SystemExit("FRED-MD download failed for vintage " + vintage + ":\n  " + "\n  ".join(errors)
                     + "\nVerify the download location on the St. Louis Fed FRED-MD page (spec §6 Stage 1).")


def write_data_sheet(blocks: dict, path: Path) -> None:
    cells = blocks["outliers"].groupby("series").size()
    rows = ["# FRED-MD data sheet (generated by run.py)", "",
            "| series | block | t-code | first | last | outlier cells removed |", "|---|---|---|---|---|---|"]
    for block_name, cols in [("growth", GROWTH_BLOCK), ("inflation", INFLATION_BLOCK)]:
        df = blocks[block_name]
        for c in cols:
            if c not in df:
                continue
            s = df[c].dropna()
            rows.append(f"| {c} | {block_name} | {int(blocks['tcodes'][c])} | {s.index[0]:%Y-%m} | {s.index[-1]:%Y-%m} | {int(cells.get(c, 0))} |")
    rows += ["", f"Missing from vintage: {blocks['missing_series'] or 'none'}",
             f"Estimation mask excludes {int((~blocks['estimation_mask']).sum())} months."]
    Path(path).write_text("\n".join(rows) + "\n", encoding="utf-8")


def robustness_table(path: str, **kw) -> dict:
    """Spec §6 Stage 2: labels under alternative trends; agreement matrix, revision stats, GFC share."""
    variants = {"120_mean": dict(window=120), "180_mean": dict(window=180), "240_mean": dict(window=240),
                "120_median": dict(window=120, method="trailing_median"),
                "180_median": dict(window=180, method="trailing_median"),
                "hamilton": dict(method="hamilton")}
    runs = {k: run_pipeline(path, **{**kw, **v}) for k, v in variants.items()}
    names = list(runs)
    agree = pd.DataFrame(index=names, columns=names, dtype=float)
    for a in names:
        for b in names:
            la, lb = runs[a].hmm.labels_filtered, runs[b].hmm.labels_filtered
            idx = la.index.intersection(lb.index)
            agree.loc[a, b] = float((la.loc[idx] == lb.loc[idx]).mean())
    per = {}
    for k, r in runs.items():
        expost = centred_trend_expost(r.growth_factor["factor"], smooth=r.params["smooth"], window=r.params["window"])
        per[k] = {**revision_stats(r.G, expost),
                  "gfc_contraction_hmm": acceptance.share(r.hmm.labels_filtered, "2008-09", "2009-06", ["Contraction"]),
                  "counts_2024_26": r.hmm.labels_filtered.loc["2024-01":"2026-12"].value_counts().to_dict(),
                  "mean_growth_gap_2024_26": float(r.G.loc["2024-01":"2026-12"].mean())}
    return {"label_agreement": agree.round(3).to_dict(orient="index"), "per_variant": per}


def build_summary(res, free, gmm, wf, hist_labels, hist_probs, label_source, table, rev, lags, extra) -> dict:
    hmm = res.hmm
    return {
        "n_months": int(len(hist_labels)),
        "sample": [str(hist_labels.index[0].date()), str(hist_labels.index[-1].date())],
        "label_source": label_source,
        "quadrant_source": "walk-forward gaps" if wf is not None else "full-sample",
        "params": {k: (list(v) if isinstance(v, tuple) else v) for k, v in res.params.items()},
        "regime_counts": hist_labels.value_counts().to_dict(),
        "regime_counts_quadrants": res.quadrant.value_counts().to_dict(),
        "agreement_with_quadrants": float((hist_labels == res.quadrant.reindex(hist_labels.index)).mean()),
        "emission_only_agreement": float((hmm.emission_labels == res.quadrant0).mean()),
        "filtered_vs_smoothed_agreement": float((hmm.labels_filtered == hmm.labels_smoothed_expost).mean()),
        "share_max_prob_gt_095": {"primary": float((hist_probs.max(axis=1) > 0.95).mean()),
                                  "smoothed_expost": float((hmm.probs_smoothed_expost.max(axis=1) > 0.95).mean())},
        "expected_duration_months": R.expected_duration(hmm.transmat).round(2).to_dict(),
        "mean_run_length_months": R.run_lengths(hist_labels).round(1).to_dict(),
        "transition_matrix": hmm.transmat.round(4).to_dict(orient="index"),
        "min_transition_prob": float(hmm.transmat.to_numpy().min()),
        "emission_means": {r: [round(float(x), 3) for x in hmm.means[i]] for i, r in enumerate(R.REGIMES)},
        "free_hmm": {"state_names": list(free.state_map.values()),
                     "quadrant_profile": free.quadrant_profile.round(3).to_dict(orient="index"),
                     "agreement_marginalised_vs_quadrants": float((free.quadrant_probs_filtered.idxmax(axis=1) == res.quadrant0).mean())},
        "gmm": {"cluster_names": gmm.cluster_names,
                "quadrant_profile": gmm.quadrant_profile.round(3).to_dict(orient="index"),
                "agreement_marginalised_vs_quadrants": float((gmm.quadrant_probs.idxmax(axis=1) == res.quadrant0).mean())},
        "stagflation_1973_75": acceptance.share(hist_labels, "1973-11", "1975-03", ["Stagflation"]),
        "stagflation_1980_82": acceptance.share(hist_labels, "1980-01", "1982-11", ["Stagflation"]),
        "growth_gap_revision": rev,
        "nber_lags_rt": lags.to_dict(orient="records") if lags is not None else None,
        "walkforward": None if wf is None else {"n_months": int(len(wf.labels_rt)),
                                                "start": str(wf.labels_rt.index[0].date())},
        "loadings": {"growth": res.growth_loadings.round(3).to_dict(), "inflation": res.inflation_loadings.round(3).to_dict()},
        "acceptance_tests": table.reset_index().to_dict(orient="records"),
        "acceptance_all_passed": bool(acceptance.all_passed(table)),
        "acceptance_known_failures": {name: acceptance.KNOWN_FAILURES[name] for name in table.index
                                       if table.loc[name, "known_failure"] and not table.loc[name, "passed"]},
        "acceptance_blocking_failures": acceptance.blocking_failures(table),
        **extra,
    }


def publish(staging: Path, out_dir: Path, figs_dir: Path) -> None:
    """Move staged results into place with directory renames.

    The new tree is copied to <dst>.new first, then the old tree is renamed to
    <dst>.old and the new one renamed into place, so an interruption leaves
    either the previous outputs or the new ones, never a half-copied mix.
    """
    for src, dst in [(staging / "output", out_dir), (staging / "figs", figs_dir)]:
        new, old = dst.with_name(dst.name + ".new"), dst.with_name(dst.name + ".old")
        for leftover in (new, old):
            if leftover.exists():
                shutil.rmtree(leftover)
        shutil.copytree(src, new)
        if dst.exists():
            dst.rename(old)
        new.rename(dst)
        if old.exists():
            shutil.rmtree(old)
    shutil.rmtree(staging)


def clear_asset_artefacts(out_dir: Path, figs_dir: Path) -> None:
    """Remove every asset artefact a previous run published (plus any staging left behind)."""
    for name in ASSET_CSVS:
        (out_dir / name).unlink(missing_ok=True)
    for pattern in ASSET_CSV_GLOBS:
        for p in out_dir.glob(pattern):
            p.unlink()
    for name in ASSET_FIGS:
        (figs_dir / f"{name}.png").unlink(missing_ok=True)
    for d in (out_dir / ASSETS_STAGING, figs_dir / ASSETS_STAGING):
        if d.exists():
            shutil.rmtree(d)


def run_assets(labels_df: pd.DataFrame, probs_rt: pd.DataFrame, out_dir: Path, figs_dir: Path,
               returns_cache: Path, refresh: bool, placebo_n: int, skip_placebo: bool) -> dict:
    """Stage 5-6 after the engine has published. Returns the summary['assets'] block.

    The whole stage runs inside one try/except: publish() has already swapped
    output/ into place by the time this is called, so a failure anywhere here
    (network, cache, a computation, or a figure write) must not change the
    engine's exit code -- it is reported via the "skipped" key instead.

    Publication is all-or-nothing. The previous run's asset artefacts are
    removed up front, everything is written to <dir>/.assets_staging, and the
    files are moved into place only once the whole stage has succeeded, so a
    mid-stage failure can never leave this run's early files sitting beside the
    previous run's late ones.
    """
    if not labels_df["hmm_walkforward"].notna().any():
        return {"skipped": "walk-forward disabled: the asset stage needs real-time labels"}
    stage_out, stage_figs = out_dir / ASSETS_STAGING, figs_dir / ASSETS_STAGING
    try:
        clear_asset_artefacts(out_dir, figs_dir)
        stage_out.mkdir(parents=True); stage_figs.mkdir(parents=True)
        rets = assets.load_returns(cache=returns_cache, refresh=refresh)
        table = assets.regime_conditional_table(rets, labels_df, "hmm_walkforward")
        table.to_csv(stage_out / "regime_returns.csv")
        corr = assets.conditional_corr(rets, labels_df, "hmm_walkforward")
        for reg, c in corr.items():
            c.to_csv(stage_out / f"regime_corr_{reg}.csv")
        mu, cov = assets.regime_moments(rets, labels_df, "hmm_walkforward")
        aligned = assets.align_to_available(rets, labels_df, "hmm_walkforward")
        r6040 = assets.portfolio_returns(aligned.drop(columns=["label", "label_date"]), assets.W6040)
        gaps = pd.concat([assets.align_to_available(rets, labels_df, "growth_gap")["label"].rename("growth_gap"),
                          assets.align_to_available(rets, labels_df, "inflation_gap")["label"].rename("inflation_gap")], axis=1)
        growth = assets.growth_share_6040(pd.concat([r6040.rename("r6040"), gaps], axis=1))
        spread = assets.sharpe_spread_placebo(pd.DataFrame({"label": aligned["label"], "r6040": r6040}), n=1000)
        probs_avail = probs_rt.reindex(labels_df.index).dropna(how="all")
        path_df = assets.mixture_path(mu, cov, probs_avail.loc[probs_avail.index >= rets.index[0]], pd.Series(assets.W6040))
        # fig9 is descriptive, but its x-axis must still be honest: index the path by the
        # month each number could first have been known (label date + publication lag).
        path_df.index = pd.DatetimeIndex(labels_df["available_at"].reindex(path_df.index), name="available_at")
        bts = {f"cost_bp_{c}": portfolio.backtest(rets, labels_df, probs_rt, cost_bp=float(c)) for c in (0, 10)}
        bt0 = bts["cost_bp_0"]
        bt0.returns.to_csv(stage_out / "backtest_returns.csv")
        pd.concat({s: bt0.weights[s] for s in ("PIT_MaxSharpe", "ProbWeighted_MaxSharpe")}, axis=1).to_csv(stage_out / "portfolio_weights.csv")
        look = portfolio.lookahead_decomposition(bt0.perf)
        plc = None if skip_placebo else portfolio.backtest_placebo(rets, labels_df, probs_rt, n=placebo_n)
        figures.fig8_regime_returns(table, str(stage_figs / "fig8_regime_returns.png"))
        figures.fig9_mixture_6040(path_df, str(stage_figs / "fig9_mixture_6040.png"))
        figures.fig10_backtest_wealth(bt0.returns, str(stage_figs / "fig10_backtest_wealth.png"))
        figures.fig11_pit_weights(bt0.weights["PIT_MaxSharpe"], str(stage_figs / "fig11_pit_weights.png"))
        n_per = table.xs(rets.columns[0], level="asset")["n"].astype(int).to_dict()
        block = {
            "skipped": None, "universe": assets.UNIVERSE,
            "window": {"start": str(aligned.index[0].date()), "end": str(aligned.index[-1].date()), "n_months": int(len(aligned))},
            "n_per_regime": n_per,
            "growth_share_6040": growth,
            "sharpe_spread_placebo": {"real": spread["real"], "percentile": spread["percentile"]},
            "backtest": {k: {"perf": v.perf.round(4).to_dict(orient="index"), "counters": v.counters, "params": v.params}
                         for k, v in bts.items()},
            "lookahead": look,
            "backtest_placebo": None if plc is None else {"real": plc["real"], "percentile": plc["percentile"], "n": plc["n"]},
        }
        for staged, dest in ((stage_out, out_dir), (stage_figs, figs_dir)):
            for src in sorted(staged.iterdir()):
                shutil.move(str(src), str(dest / src.name))
            staged.rmdir()
        return block
    except Exception as e:  # asset-stage failure anywhere must not change the engine's exit code
        for d in (stage_out, stage_figs):
            if d.exists():
                shutil.rmtree(d, ignore_errors=True)
        return {"skipped": f"{type(e).__name__}: {e}"}


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("path", nargs="?")
    ap.add_argument("--vintage")
    ap.add_argument("--trend-window", type=int, default=DEFAULTS["window"])
    ap.add_argument("--theta", type=float, default=DEFAULTS["theta"])
    ap.add_argument("--no-walkforward", action="store_true")
    ap.add_argument("--wf-step", type=int, default=1)
    ap.add_argument("--wf-min-obs", type=int, default=240)
    ap.add_argument("--skip-robustness", action="store_true")
    ap.add_argument("--skip-expanding", action="store_true")
    ap.add_argument("--out-dir", default=str(HERE / "output"))
    ap.add_argument("--figs-dir", default=str(HERE / "figs"))
    ap.add_argument("--data-sheet", default=str(HERE / "data" / "README.md"))
    ap.add_argument("--no-assets", action="store_true")
    ap.add_argument("--returns-cache", default=str(HERE / "data" / "returns_yfinance.parquet"))
    ap.add_argument("--refresh-returns", action="store_true")
    ap.add_argument("--placebo-n", type=int, default=200)
    ap.add_argument("--skip-placebo", action="store_true")
    a = ap.parse_args(argv)
    path = str(download_vintage(a.vintage, HERE / "data")) if a.vintage else a.path
    if not path:
        ap.error("give a FRED-MD csv path or --vintage YYYY-MM")
    kw = dict(window=a.trend_window, theta=a.theta)
    out_dir, figs_dir = Path(a.out_dir), Path(a.figs_dir)
    staging = out_dir.parent / (out_dir.name + ".staging")
    if staging.exists():
        shutil.rmtree(staging)
    (staging / "output").mkdir(parents=True); (staging / "figs").mkdir(parents=True)

    res = run_pipeline(path, **kw)
    print(f"sample {res.hmm.labels_filtered.index[0]:%Y-%m}..{res.hmm.labels_filtered.index[-1]:%Y-%m}; "
          f"outliers removed {len(res.blocks['outliers'])}; masked months {int((~res.est_mask).sum())}")
    free = R.fit_free_hmm4(res.G, res.P, res.est_mask, persistence=res.params["persistence"], eps=res.params["eps"])
    gmm = R.fit_gmm4(res.G, res.P, res.est_mask)

    wf = None
    if not a.no_walkforward:
        wf = fit_hmm4_walkforward(path, min_obs=a.wf_min_obs, step=a.wf_step,
                                  progress=lambda i, n, t: print(f"\rwalk-forward {i}/{n} {t:%Y-%m}", end=""), **kw)
        print()
    if wf is not None:
        hist_labels, hist_probs, label_source = wf.labels_rt, wf.probs_rt, "walk-forward filtered"
    else:
        hist_labels, hist_probs, label_source = res.hmm.labels_filtered, res.hmm.probs_filtered, "full-sample filtered (walk-forward disabled)"
    quad_hist = (R.quadrant_labels(wf.growth_gap_rt, wf.inflation_gap_rt, a.theta) if wf is not None
                 else res.quadrant)

    vals = {}
    vals.update(acceptance.history_metrics(hist_labels, quad_hist.reindex(hist_labels.index), hist_probs))
    vals.update(acceptance.model_metrics(res))
    vals.update(acceptance.truncation_metrics(path, **kw))
    vals["seed_invariance_disagreements"] = acceptance.seed_metric(path, **kw)
    table = acceptance.evaluate(vals)
    print(table.to_string())

    fig = lambda n: str(staging / "figs" / f"{n}.png")
    figures.fig1_factors_gaps(res, fig(FIG_NAMES[0]))
    figures.fig2_regime_timeline(res, wf, free, gmm, fig(FIG_NAMES[1]))
    figures.fig3_state_space(res, wf, fig(FIG_NAMES[2]))
    figures.fig4_hmm_probabilities(res, wf, fig(FIG_NAMES[3]))
    rev = figures.fig5_revisions(res, fig(FIG_NAMES[4]))
    figures.fig6_classifier_comparison(res, free, gmm, fig(FIG_NAMES[5]))
    lags = figures.fig7_walkforward(res, wf, fig(FIG_NAMES[6])) if wf is not None else None

    extra = {}
    if not a.skip_robustness:
        extra["robustness"] = robustness_table(path, theta=a.theta)
    if not a.skip_expanding:
        ep, loads = pca_factor_expanding(res.blocks["growth"], "INDPRO", res.est_mask)
        extra["expanding_loadings"] = {"indpro_loading_range": [float(loads["INDPRO"].min()), float(loads["INDPRO"].max())],
                                       "endpoint_vs_full_factor_corr": float(pd.concat([ep["factor"], res.growth_factor["factor"]], axis=1).dropna().corr().iloc[0, 1])}
    summary = build_summary(res, free, gmm, wf, hist_labels, hist_probs, label_source, table, rev, lags, extra)

    parts = [pd.Series(pd.NA, index=res.hmm.labels_filtered.index, name="hmm_walkforward") if wf is None else wf.labels_rt,
             quad_hist.rename("quadrant_walkforward") if wf is not None
             else pd.Series(pd.NA, index=res.hmm.labels_filtered.index, name="quadrant_walkforward"),
             free.labels_filtered.rename("hmm_free"), gmm.labels.rename("gmm"),
             (res.hmm.probs_filtered if wf is None else wf.probs_rt).add_prefix("p_")]
    labels_df = labels_frame(res, extra=parts)
    labels_df.to_csv(staging / "output" / "regime_labels.csv")
    res.blocks["outliers"].to_csv(staging / "output" / "outliers_removed.csv", index=False)
    table.to_csv(staging / "output" / "acceptance.csv")
    (staging / "output" / "summary.json").write_text(json.dumps(summary, indent=2, default=str), encoding="utf-8")
    write_data_sheet(res.blocks, a.data_sheet)

    if not acceptance.all_passed(table):
        print(f"ACCEPTANCE FAILED ({acceptance.blocking_failures(table)}) — outputs left in {staging}; {out_dir} untouched", file=sys.stderr)
        return 1
    publish(staging, out_dir, figs_dir)
    print(f"published to {out_dir} and {figs_dir}")

    if not a.no_assets:
        probs_src = wf.probs_rt if wf is not None else res.hmm.probs_filtered
        block = run_assets(labels_df, probs_src, out_dir, figs_dir, Path(a.returns_cache), a.refresh_returns,
                           a.placebo_n, a.skip_placebo)
        if block.get("skipped") is None:
            # Promoting the metrics into the acceptance table is part of the stage: if it
            # fails, the stage degrades to "skipped" like any other asset-stage failure
            # (and drops its artefacts) rather than leaving a half-updated acceptance.csv.
            try:
                perf0 = block["backtest"]["cost_bp_0"]["perf"]
                perf10 = block["backtest"]["cost_bp_10"]["perf"]
                vals.update({"pit_sharpe": block["lookahead"]["pit_sharpe"], "oracle_sharpe": block["lookahead"]["oracle_sharpe"],
                             "insample_sharpe": block["lookahead"]["insample_sharpe"],
                             "label_lookahead": block["lookahead"]["label_lookahead"],
                             "moment_lookahead": block["lookahead"]["moment_lookahead"],
                             "growth_share_6040": block["growth_share_6040"]["growth_share"],
                             "growth_share_6040_r2": block["growth_share_6040"]["r2"],
                             "static_6040_sharpe": perf0["Static_6040"]["sharpe"],
                             "pit_sharpe_10bp": perf10["PIT_MaxSharpe"]["sharpe"],
                             "backtest_placebo_pct": (block["backtest_placebo"] or {}).get("percentile", float("nan"))})
                table = acceptance.evaluate(vals)
                table.to_csv(out_dir / "acceptance.csv")
                summary["acceptance_tests"] = table.reset_index().to_dict(orient="records")
            except Exception as e:
                clear_asset_artefacts(out_dir, figs_dir)
                block = {"skipped": f"{type(e).__name__}: {e}"}
        summary["assets"] = block
        if block.get("skipped") is not None:
            print(f"asset stage skipped: {block['skipped']}", file=sys.stderr)
        (out_dir / "summary.json").write_text(json.dumps(summary, indent=2, default=str), encoding="utf-8")
        print("asset stage " + ("skipped" if block.get("skipped") else "published"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
