"""End-to-end driver (spec §5 outputs, §8 acceptance, §12 staged publish).

Usage:
  python run.py data/fredmd_2026-07.csv
  python run.py --vintage 2026-08            # downloads data/fredmd_2026-08.csv first
Options: --trend-window 120 --theta 0.5 --no-walkforward --wf-step 1 --wf-min-obs 240
         --skip-robustness --skip-expanding --out-dir output --figs-dir figs --data-sheet data/README.md
Exit code 1 and no publish if any §8 threshold fails; staged results stay in <out-dir>.staging/.
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
import urllib.request
from pathlib import Path

import numpy as np
import pandas as pd

from regime_v2 import acceptance, figures, regimes as R
from regime_v2.data import GROWTH_BLOCK, INFLATION_BLOCK
from regime_v2.factors import pca_factor_expanding
from regime_v2.pipeline import DEFAULTS, labels_frame, run_pipeline
from regime_v2.trend import centred_trend_expost, revision_stats
from regime_v2.walkforward import fit_hmm4_walkforward

HERE = Path(__file__).resolve().parent
# Spec §6 Stage 1: the download location is UNVERIFIED (both patterns returned 403
# on 2026-09-04). Both are tried in order; confirm on the St. Louis Fed site before
# relying on --vintage for the §12 refresh.
FREDMD_URLS = [
    "https://files.stlouisfed.org/files/htdocs/fred-md/monthly/{vintage}.csv",
    "https://www.stlouisfed.org/-/media/project/frbstl/stlouisfed/research/fred-md/monthly/{vintage}.csv",
]
FREDMD_URL = FREDMD_URLS[0]   # kept for callers/tests that format a single pattern
FIG_NAMES = ["fig1_factors_gaps", "fig2_regime_timeline", "fig3_state_space", "fig4_hmm_probabilities",
             "fig5_revisions", "fig6_classifier_comparison", "fig7_walkforward"]


def download_vintage(vintage: str, dest_dir: Path, fetch=urllib.request.urlopen) -> Path:
    """Download one FRED-MD vintage, trying each known URL pattern in turn."""
    dest_dir = Path(dest_dir); dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / f"fredmd_{vintage}.csv"
    errors = []
    for template in FREDMD_URLS:
        url = template.format(vintage=vintage)
        try:
            with fetch(url, timeout=60) as r:
                dest.write_bytes(r.read())
            return dest
        except Exception as e:  # urllib.error.HTTPError / URLError / OSError
            errors.append(f"{url}: {e}")
    raise SystemExit("FRED-MD download failed for vintage " + vintage + ":\n  " + "\n  ".join(errors)
                     + "\nVerify the download location on the St. Louis Fed FRED-MD page (spec §6 Stage 1).")


def write_data_sheet(blocks: dict, path: Path) -> None:
    cells = blocks["outliers"].groupby("series").size()
    rows = ["# FRED-MD data sheet (generated by run.py)", "",
            "| series | block | t-code | first | last | outlier cells removed |", "|---|---|---|---|---|---|"]
    for block_name, cols in [("growth", GROWTH_BLOCK), ("inflation", INFLATION_BLOCK)]:
        df = blocks[block_name]
        for c in cols:
            if c not in df:
                continue
            s = df[c].dropna()
            rows.append(f"| {c} | {block_name} | {int(blocks['tcodes'][c])} | {s.index[0]:%Y-%m} | {s.index[-1]:%Y-%m} | {int(cells.get(c, 0))} |")
    rows += ["", f"Missing from vintage: {blocks['missing_series'] or 'none'}",
             f"Estimation mask excludes {int((~blocks['estimation_mask']).sum())} months."]
    Path(path).write_text("\n".join(rows) + "\n", encoding="utf-8")


def robustness_table(path: str, **kw) -> dict:
    """Spec §6 Stage 2: labels under alternative trends; agreement matrix, revision stats, GFC share."""
    variants = {"120_mean": dict(window=120), "180_mean": dict(window=180), "240_mean": dict(window=240),
                "120_median": dict(window=120, method="trailing_median"),
                "180_median": dict(window=180, method="trailing_median"),
                "hamilton": dict(method="hamilton")}
    runs = {k: run_pipeline(path, **{**kw, **v}) for k, v in variants.items()}
    names = list(runs)
    agree = pd.DataFrame(index=names, columns=names, dtype=float)
    for a in names:
        for b in names:
            la, lb = runs[a].hmm.labels_filtered, runs[b].hmm.labels_filtered
            idx = la.index.intersection(lb.index)
            agree.loc[a, b] = float((la.loc[idx] == lb.loc[idx]).mean())
    per = {}
    for k, r in runs.items():
        expost = centred_trend_expost(r.growth_factor["factor"], smooth=r.params["smooth"], window=r.params["window"])
        per[k] = {**revision_stats(r.G, expost),
                  "gfc_contraction_hmm": acceptance.share(r.hmm.labels_filtered, "2008-09", "2009-06", ["Contraction"]),
                  "counts_2024_26": r.hmm.labels_filtered.loc["2024-01":"2026-12"].value_counts().to_dict(),
                  "mean_growth_gap_2024_26": float(r.G.loc["2024-01":"2026-12"].mean())}
    return {"label_agreement": agree.round(3).to_dict(orient="index"), "per_variant": per}


def build_summary(res, free, gmm, wf, hist_labels, hist_probs, label_source, table, rev, lags, extra) -> dict:
    hmm = res.hmm
    return {
        "n_months": int(len(hist_labels)),
        "sample": [str(hist_labels.index[0].date()), str(hist_labels.index[-1].date())],
        "label_source": label_source,
        "quadrant_source": "walk-forward gaps" if wf is not None else "full-sample",
        "params": {k: (list(v) if isinstance(v, tuple) else v) for k, v in res.params.items()},
        "regime_counts": hist_labels.value_counts().to_dict(),
        "regime_counts_quadrants": res.quadrant.value_counts().to_dict(),
        "agreement_with_quadrants": float((hist_labels == res.quadrant.reindex(hist_labels.index)).mean()),
        "emission_only_agreement": float((hmm.emission_labels == res.quadrant0).mean()),
        "filtered_vs_smoothed_agreement": float((hmm.labels_filtered == hmm.labels_smoothed_expost).mean()),
        "share_max_prob_gt_095": {"primary": float((hist_probs.max(axis=1) > 0.95).mean()),
                                  "smoothed_expost": float((hmm.probs_smoothed_expost.max(axis=1) > 0.95).mean())},
        "expected_duration_months": R.expected_duration(hmm.transmat).round(2).to_dict(),
        "mean_run_length_months": R.run_lengths(hist_labels).round(1).to_dict(),
        "transition_matrix": hmm.transmat.round(4).to_dict(orient="index"),
        "min_transition_prob": float(hmm.transmat.to_numpy().min()),
        "emission_means": {r: [round(float(x), 3) for x in hmm.means[i]] for i, r in enumerate(R.REGIMES)},
        "free_hmm": {"state_names": list(free.state_map.values()),
                     "quadrant_profile": free.quadrant_profile.round(3).to_dict(orient="index"),
                     "agreement_marginalised_vs_quadrants": float((free.quadrant_probs_filtered.idxmax(axis=1) == res.quadrant0).mean())},
        "gmm": {"cluster_names": gmm.cluster_names,
                "quadrant_profile": gmm.quadrant_profile.round(3).to_dict(orient="index"),
                "agreement_marginalised_vs_quadrants": float((gmm.quadrant_probs.idxmax(axis=1) == res.quadrant0).mean())},
        "stagflation_1973_75": acceptance.share(hist_labels, "1973-11", "1975-03", ["Stagflation"]),
        "stagflation_1980_82": acceptance.share(hist_labels, "1980-01", "1982-11", ["Stagflation"]),
        "growth_gap_revision": rev,
        "nber_lags_rt": lags.to_dict(orient="records") if lags is not None else None,
        "walkforward": None if wf is None else {"n_months": int(len(wf.labels_rt)),
                                                "start": str(wf.labels_rt.index[0].date())},
        "loadings": {"growth": res.growth_loadings.round(3).to_dict(), "inflation": res.inflation_loadings.round(3).to_dict()},
        "acceptance_tests": table.reset_index().to_dict(orient="records"),
        "acceptance_all_passed": bool(acceptance.all_passed(table)),
        "acceptance_known_failures": {name: acceptance.KNOWN_FAILURES[name] for name in table.index
                                       if table.loc[name, "known_failure"] and not table.loc[name, "passed"]},
        "acceptance_blocking_failures": acceptance.blocking_failures(table),
        **extra,
    }


def publish(staging: Path, out_dir: Path, figs_dir: Path) -> None:
    """Move staged results into place with directory renames.

    The new tree is copied to <dst>.new first, then the old tree is renamed to
    <dst>.old and the new one renamed into place, so an interruption leaves
    either the previous outputs or the new ones, never a half-copied mix.
    """
    for src, dst in [(staging / "output", out_dir), (staging / "figs", figs_dir)]:
        new, old = dst.with_name(dst.name + ".new"), dst.with_name(dst.name + ".old")
        for leftover in (new, old):
            if leftover.exists():
                shutil.rmtree(leftover)
        shutil.copytree(src, new)
        if dst.exists():
            dst.rename(old)
        new.rename(dst)
        if old.exists():
            shutil.rmtree(old)
    shutil.rmtree(staging)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("path", nargs="?")
    ap.add_argument("--vintage")
    ap.add_argument("--trend-window", type=int, default=DEFAULTS["window"])
    ap.add_argument("--theta", type=float, default=DEFAULTS["theta"])
    ap.add_argument("--no-walkforward", action="store_true")
    ap.add_argument("--wf-step", type=int, default=1)
    ap.add_argument("--wf-min-obs", type=int, default=240)
    ap.add_argument("--skip-robustness", action="store_true")
    ap.add_argument("--skip-expanding", action="store_true")
    ap.add_argument("--out-dir", default=str(HERE / "output"))
    ap.add_argument("--figs-dir", default=str(HERE / "figs"))
    ap.add_argument("--data-sheet", default=str(HERE / "data" / "README.md"))
    a = ap.parse_args(argv)
    path = str(download_vintage(a.vintage, HERE / "data")) if a.vintage else a.path
    if not path:
        ap.error("give a FRED-MD csv path or --vintage YYYY-MM")
    kw = dict(window=a.trend_window, theta=a.theta)
    out_dir, figs_dir = Path(a.out_dir), Path(a.figs_dir)
    staging = out_dir.parent / (out_dir.name + ".staging")
    if staging.exists():
        shutil.rmtree(staging)
    (staging / "output").mkdir(parents=True); (staging / "figs").mkdir(parents=True)

    res = run_pipeline(path, **kw)
    print(f"sample {res.hmm.labels_filtered.index[0]:%Y-%m}..{res.hmm.labels_filtered.index[-1]:%Y-%m}; "
          f"outliers removed {len(res.blocks['outliers'])}; masked months {int((~res.est_mask).sum())}")
    free = R.fit_free_hmm4(res.G, res.P, res.est_mask, persistence=res.params["persistence"], eps=res.params["eps"])
    gmm = R.fit_gmm4(res.G, res.P, res.est_mask)

    wf = None
    if not a.no_walkforward:
        wf = fit_hmm4_walkforward(path, min_obs=a.wf_min_obs, step=a.wf_step,
                                  progress=lambda i, n, t: print(f"\rwalk-forward {i}/{n} {t:%Y-%m}", end=""), **kw)
        print()
    if wf is not None:
        hist_labels, hist_probs, label_source = wf.labels_rt, wf.probs_rt, "walk-forward filtered"
    else:
        hist_labels, hist_probs, label_source = res.hmm.labels_filtered, res.hmm.probs_filtered, "full-sample filtered (walk-forward disabled)"
    quad_hist = (R.quadrant_labels(wf.growth_gap_rt, wf.inflation_gap_rt, a.theta) if wf is not None
                 else res.quadrant)

    vals = {}
    vals.update(acceptance.history_metrics(hist_labels, quad_hist.reindex(hist_labels.index), hist_probs))
    vals.update(acceptance.model_metrics(res))
    vals.update(acceptance.truncation_metrics(path, **kw))
    vals["seed_invariance_disagreements"] = acceptance.seed_metric(path, **kw)
    table = acceptance.evaluate(vals)
    print(table.to_string())

    fig = lambda n: str(staging / "figs" / f"{n}.png")
    figures.fig1_factors_gaps(res, fig(FIG_NAMES[0]))
    figures.fig2_regime_timeline(res, wf, free, gmm, fig(FIG_NAMES[1]))
    figures.fig3_state_space(res, wf, fig(FIG_NAMES[2]))
    figures.fig4_hmm_probabilities(res, wf, fig(FIG_NAMES[3]))
    rev = figures.fig5_revisions(res, fig(FIG_NAMES[4]))
    figures.fig6_classifier_comparison(res, free, gmm, fig(FIG_NAMES[5]))
    lags = figures.fig7_walkforward(res, wf, fig(FIG_NAMES[6])) if wf is not None else None

    extra = {}
    if not a.skip_robustness:
        extra["robustness"] = robustness_table(path, theta=a.theta)
    if not a.skip_expanding:
        ep, loads = pca_factor_expanding(res.blocks["growth"], "INDPRO", res.est_mask)
        extra["expanding_loadings"] = {"indpro_loading_range": [float(loads["INDPRO"].min()), float(loads["INDPRO"].max())],
                                       "endpoint_vs_full_factor_corr": float(pd.concat([ep["factor"], res.growth_factor["factor"]], axis=1).dropna().corr().iloc[0, 1])}
    summary = build_summary(res, free, gmm, wf, hist_labels, hist_probs, label_source, table, rev, lags, extra)

    parts = [pd.Series(pd.NA, index=res.hmm.labels_filtered.index, name="hmm_walkforward") if wf is None else wf.labels_rt,
             quad_hist.rename("quadrant_walkforward") if wf is not None
             else pd.Series(pd.NA, index=res.hmm.labels_filtered.index, name="quadrant_walkforward"),
             free.labels_filtered.rename("hmm_free"), gmm.labels.rename("gmm"),
             (res.hmm.probs_filtered if wf is None else wf.probs_rt).add_prefix("p_")]
    labels_frame(res, extra=parts).to_csv(staging / "output" / "regime_labels.csv")
    res.blocks["outliers"].to_csv(staging / "output" / "outliers_removed.csv", index=False)
    table.to_csv(staging / "output" / "acceptance.csv")
    (staging / "output" / "summary.json").write_text(json.dumps(summary, indent=2, default=str), encoding="utf-8")
    write_data_sheet(res.blocks, a.data_sheet)

    if not acceptance.all_passed(table):
        print(f"ACCEPTANCE FAILED ({acceptance.blocking_failures(table)}) — outputs left in {staging}; {out_dir} untouched", file=sys.stderr)
        return 1
    publish(staging, out_dir, figs_dir)
    print(f"published to {out_dir} and {figs_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
